import Image2 from "../../assets/Images/image2.jpg";

export const tabs = [
  "Cancellation", 
  "Account Change",
  "Provider Registration",
];

export const tabJobCards = {
  Cancellation: [
    {
      id: 1,
      title: "Carpenter",
      jobId: "#JCD003",
      status: "Cancellation request",
      client: "Robert Wilson",
      languages: "English, French",
      location: "Chicago",
      date: "Friday - April 25, 2025",
      time: "10:00 AM",
      jobType: "Carpenter",
      image: Image2,
      statusColor: "bg-red-500",
      statusBg: "bg-red-50",
      statusText: "text-red-700",
      Button: "Cancel Job",
    },
    {
      id: 2,
      title: "Carpenter",
      jobId: "#JCD003",
      status: "Cancellation request",
      client: "Robert Wilson",
      languages: "English, French",
      location: "Chicago",
      date: "Friday - April 25, 2025",
      time: "10:00 AM",
      jobType: "Carpenter",
      image: Image2,
      statusColor: "bg-red-500",
      statusBg: "bg-red-50",
      statusText: "text-red-700",
      Button: "Cancel Job",
    },
    {
      id: 3,
      title: "Carpenter",
      jobId: "#JCD003",
      status: "Cancellation request",
      client: "Robert Wilson",
      languages: "English, French",
      location: "Chicago",
      date: "Friday - April 25, 2025",
      time: "10:00 AM",
      jobType: "Carpenter",
      image: Image2,
      statusColor: "bg-red-500",
      statusBg: "bg-red-50",
      statusText: "text-red-700",
      Button: "Cancel Job",
    },
    {
      id: 4,
      title: "Carpenter",
      jobId: "#JCD003",
      status: "Cancellation request",
      client: "Robert Wilson",
      languages: "English, French",
      location: "Chicago",
      date: "Friday - April 25, 2025",
      time: "10:00 AM",
      jobType: "Carpenter",
      image: Image2,
      statusColor: "bg-red-500",
      statusBg: "bg-red-50",
      statusText: "text-red-700",
      Button: "Cancel Job",
    },
    {
      id: 5,
      title: "Carpenter",
      jobId: "#JCD003",
      status: "Cancellation request",
      client: "Robert Wilson",
      languages: "English, French",
      location: "Chicago",
      date: "Friday - April 25, 2025",
      time: "10:00 AM",
      jobType: "Carpenter",
      image: Image2,
      statusColor: "bg-red-500",
      statusBg: "bg-red-50",
      statusText: "text-red-700",
      Button: "Cancel Job",
    },
    {
      id: 6,
      title: "Carpenter",
      jobId: "#JCD003",
      status: "Cancellation request",
      client: "Robert Wilson",
      languages: "English, French",
      location: "Chicago",
      date: "Friday - April 25, 2025",
      time: "10:00 AM",
      jobType: "Carpenter",
      image: Image2,
      statusColor: "bg-red-500",
      statusBg: "bg-red-50",
      statusText: "text-red-700",
      Button: "Cancel Job",
    },
  ],
  "Account Change": [
    {
      id: 1,
      name: "Michael Johnson",
      role: "Customer",
      location: "San Francisco",
      message: "I would like to report an issue with the service. Unfortunately, the quality did not meet my expectations, and I need your assistance to resolve this.",
      image: Image2,
    },
    {
      id: 2,
      name: "Sarah Williams",
      role: "Customer",
      location: "New York",
      message: "The delivery was delayed by 3 days. I need to understand the reason and get compensation for the inconvenience caused.",
      image: Image2,
    },
    {
      id: 3,
      name: "Robert Chen",
      role: "Customer",
      location: "Los Angeles",
      message: "Product arrived with damaged packaging. Some items inside were also affected. Requesting replacement or refund.",
      image: Image2,
    },
    {
      id: 4,
      name: "Emma Davis",
      role: "Customer",
      location: "Chicago",
      message: "I received the wrong item in my order. The size and color don't match what I ordered. Need immediate resolution.",
      image: Image2,
    },
    {
      id: 5,
      name: "James Wilson",
      role: "Customer",
      location: "Miami",
      message: "Billing issue - I was charged twice for the same order. Please refund the duplicate charge immediately.",
      image: Image2,
    },
    {
      id: 6,
      name: "Lisa Anderson",
      role: "Customer",
      location: "Seattle",
      message: "Technical issue with the app - unable to track my order. The tracking page shows error messages constantly.",
      image: Image2,
    },
  ],
  "Provider Registration": [
    {
      id: 1,
      name: "David Miller",
      role: "Service Provider",
      location: "Austin",
      message: "New electrician registration request. Documents submitted for verification. Ready to start accepting jobs immediately.",
      image: Image2,
    },
    {
      id: 2,
      name: "Maria Garcia",
      role: "Service Provider",
      location: "Denver",
      message: "Plumber registration with 10 years experience. All certifications and licenses uploaded. Waiting for approval.",
      image: Image2,
    },
    {
      id: 3,
      name: "John Smith",
      role: "Service Provider",
      location: "Phoenix",
      message: "Carpenter seeking registration. Portfolio includes residential and commercial projects. Available full-time.",
      image: Image2,
    },
    {
      id: 4,
      name: "Lisa Brown",
      role: "Service Provider",
      location: "Portland",
      message: "HVAC technician registration. EPA certified with 8 years experience in installation and maintenance.",
      image: Image2,
    },
    {
      id: 5,
      name: "Tom Wilson",
      role: "Service Provider",
      location: "Atlanta",
      message: "Landscaper registration request. Specialized in garden design and maintenance. Business license provided.",
      image: Image2,
    },
    {
      id: 6,
      name: "Anna Taylor",
      role: "Service Provider",
      location: "Detroit",
      message: "Painter registration with insurance. Residential and commercial painting services. References available.",
      image: Image2,
    },
  ],
};