import Image2 from "../../assets/Images/image2.jpg";

export const tabs = [
  "Escalation",
  "Refund",
  "Dispute", 
];

export const tabJobCards = {
  Escalation: [
    {
      id: 1,
      title: "Plumber",
      jobId: "#JCD001",
      status: "Escalation request",
      client: "Michael John",
      languages: "English, Hindi",
      location: "San Francisco",
      date: "Wednesday - April 23, 2025",
      time: "11:30 AM",
      jobType: "Plumber",
      ServiceProvider: "Andreo Tate",
      image: Image2,
      statusColor: "bg-blue-500",
      statusBg: "bg-blue-50",
      statusText: "text-blue-700",
      Button: "View Options",
    },
    {
      id: 2,
      title: "Electrician",
      jobId: "#JCD002",
      status: "Escalation request",
      client: "Sarah Johnson",
      languages: "English, Spanish",
      location: "New York City",
      date: "Thursday - April 24, 2025",
      time: "02:45 PM",
      jobType: "Electrician",
      ServiceProvider: "Andreo Tate",
      image: Image2,
      statusColor: "bg-blue-500",
      statusBg: "bg-blue-50",
      statusText: "text-blue-700",
      Button: "View Options",
    },
    {
      id: 3,
      title: "Plumber",
      jobId: "#JCD001",
      status: "Escalation request",
      client: "Michael John",
      languages: "English, Hindi",
      location: "San Francisco",
      date: "Wednesday - April 23, 2025",
      time: "11:30 AM",
      jobType: "Plumber",
      ServiceProvider: "Andreo Tate",
      image: Image2,
      statusColor: "bg-blue-500",
      statusBg: "bg-blue-50",
      statusText: "text-blue-700",
      Button: "View Options",
    },
    {
      id: 4,
      title: "Plumber",
      jobId: "#JCD001",
      status: "Escalation request",
      client: "Michael John",
      languages: "English, Hindi",
      location: "San Francisco",
      date: "Wednesday - April 23, 2025",
      time: "11:30 AM",
      jobType: "Plumber",
      ServiceProvider: "Andreo Tate",
      image: Image2,
      statusColor: "bg-blue-500",
      statusBg: "bg-blue-50",
      statusText: "text-blue-700",
      Button: "View Options",
    },
    {
      id: 5,
      title: "Plumber",
      jobId: "#JCD001",
      status: "Escalation request",
      client: "Michael John",
      languages: "English, Hindi",
      location: "San Francisco",
      date: "Wednesday - April 23, 2025",
      time: "11:30 AM",
      jobType: "Plumber",
      ServiceProvider: "Andreo Tate",
      image: Image2,
      statusColor: "bg-blue-500",
      statusBg: "bg-blue-50",
      statusText: "text-blue-700",
      Button: "View Options",
    },
    {
      id: 6,
      title: "Plumber",
      jobId: "#JCD001",
      status: "Escalation request",
      client: "Michael John",
      languages: "English, Hindi",
      location: "San Francisco",
      date: "Wednesday - April 23, 2025",
      time: "11:30 AM",
      jobType: "Plumber",
      ServiceProvider: "Andreo Tate",
      image: Image2,
      statusColor: "bg-blue-500",
      statusBg: "bg-blue-50",
      statusText: "text-blue-700",
      Button: "View Options",
    },
  ],
  Dispute: [
    {
      id: 1,
      title: "Carpenter",
      jobId: "#JCD003",
      status: "Disputed",
      client: "Robert Wilson",
      languages: "English, French",
      location: "Chicago",
      date: "Friday - April 25, 2025",
      time: "10:00 AM",
      jobType: "Carpenter",
      image: Image2,
      statusColor: "bg-red-500",
      statusBg: "bg-red-50",
      statusText: "text-red-700",
      Button: "View Option",
    },
    {
      id: 2,
      title: "Carpenter",
      jobId: "#JCD003",
      status: "Disputed",
      client: "Robert Wilson",
      languages: "English, French",
      location: "Chicago",
      date: "Friday - April 25, 2025",
      time: "10:00 AM",
      jobType: "Carpenter",
      image: Image2,
      statusColor: "bg-red-500",
      statusBg: "bg-red-50",
      statusText: "text-red-700",
      Button: "View Option",
    },
    {
      id: 3,
      title: "Carpenter",
      jobId: "#JCD003",
      status: "Disputed",
      client: "Robert Wilson",
      languages: "English, French",
      location: "Chicago",
      date: "Friday - April 25, 2025",
      time: "10:00 AM",
      jobType: "Carpenter",
      image: Image2,
      statusColor: "bg-red-500",
      statusBg: "bg-red-50",
      statusText: "text-red-700",
      Button: "View Option",
    },
    {
      id: 4,
      title: "Carpenter",
      jobId: "#JCD003",
      status: "Disputed",
      client: "Robert Wilson",
      languages: "English, French",
      location: "Chicago",
      date: "Friday - April 25, 2025",
      time: "10:00 AM",
      jobType: "Carpenter",
      image: Image2,
      statusColor: "bg-red-500",
      statusBg: "bg-red-50",
      statusText: "text-red-700",
      Button: "View Option",
    },
    {
      id: 5,
      title: "Carpenter",
      jobId: "#JCD003",
      status: "Disputed",
      client: "Robert Wilson",
      languages: "English, French",
      location: "Chicago",
      date: "Friday - April 25, 2025",
      time: "10:00 AM",
      jobType: "Carpenter",
      image: Image2,
      statusColor: "bg-red-500",
      statusBg: "bg-red-50",
      statusText: "text-red-700",
      Button: "View Option",
    },
    {
      id: 6,
      title: "Carpenter",
      jobId: "#JCD003",
      status: "Disputed",
      client: "Robert Wilson",
      languages: "English, French",
      location: "Chicago",
      date: "Friday - April 25, 2025",
      time: "10:00 AM",
      jobType: "Carpenter",
      image: Image2,
      statusColor: "bg-red-500",
      statusBg: "bg-red-50",
      statusText: "text-red-700",
      Button: "View Option",
    },
  ],
  Refund: [
    {
      id: 1,
      title: "Electrician",
      jobId: "#JCD005",
      status: "Refund request",
      client: "Emma Watson",
      languages: "English, French",
      location: "Boston",
      date: "Tuesday - April 29, 2025",
      time: "03:30 PM",
      jobType: "Electrician",
      image: Image2,
      statusColor: "bg-[#2B2B32]",
      statusBg: "bg-[#C8C8C826]",
      statusText: "text-[#2B2B32]",
      Button: "Refund Proceed",
    },
    {
      id: 2,
      title: "Electrician",
      jobId: "#JCD005",
      status: "Refund request",
      client: "Emma Watson",
      languages: "English, French",
      location: "Boston",
      date: "Tuesday - April 29, 2025",
      time: "03:30 PM",
      jobType: "Electrician",
      image: Image2,
      statusColor: "bg-[#2B2B32]",
      statusBg: "bg-[#C8C8C826]",
      statusText: "text-[#2B2B32]",
      Button: "Refund Proceed",
    },
    {
      id: 3,
      title: "Electrician",
      jobId: "#JCD005",
      status: "Refund request",
      client: "Emma Watson",
      languages: "English, French",
      location: "Boston",
      date: "Tuesday - April 29, 2025",
      time: "03:30 PM",
      jobType: "Electrician",
      image: Image2,
      statusColor: "bg-[#2B2B32]",
      statusBg: "bg-[#C8C8C826]",
      statusText: "text-[#2B2B32]",
      Button: "Refund Proceed",
    },
    {
      id: 4,
      title: "Electrician",
      jobId: "#JCD005",
      status: "Refund request",
      client: "Emma Watson",
      languages: "English, French",
      location: "Boston",
      date: "Tuesday - April 29, 2025",
      time: "03:30 PM",
      jobType: "Electrician",
      image: Image2,
      statusColor: "bg-[#2B2B32]",
      statusBg: "bg-[#C8C8C826]",
      statusText: "text-[#2B2B32]",
      Button: "Refund Proceed",
    },
    {
      id: 5,
      title: "Electrician",
      jobId: "#JCD005",
      status: "Refund request",
      client: "Emma Watson",
      languages: "English, French",
      location: "Boston",
      date: "Tuesday - April 29, 2025",
      time: "03:30 PM",
      jobType: "Electrician",
      image: Image2,
      statusColor: "bg-[#2B2B32]",
      statusBg: "bg-[#C8C8C826]",
      statusText: "text-[#2B2B32]",
      Button: "Refund Proceed",
    },
    {
      id: 6,
      title: "Electrician",
      jobId: "#JCD005",
      status: "Refund request",
      client: "Emma Watson",
      languages: "English, French",
      location: "Boston",
      date: "Tuesday - April 29, 2025",
      time: "03:30 PM",
      jobType: "Electrician",
      image: Image2,
      statusColor: "bg-[#2B2B32]",
      statusBg: "bg-[#C8C8C826]",
      statusText: "text-[#2B2B32]",
      Button: "Refund Proceed",
    },
  ],
};